---
title: "script"
author: "Victor"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load data}
my_data <- data.table(read_csv("data/Baringo_Sites.csv"))

```




```{r Long format data frame}
my_data.long_Baringo <- my_data %>%
  pivot_longer(
    cols = starts_with(c("Land","Population", "Population D", "No.of", "Household", "Targeted")),
    names_to = "Site_Data",
    names_prefix = NULL,
    values_to = "amount",
    values_drop_na = TRUE
  )
View(my_data.long)

```


```{r Write csv}
fwrite(my_data.long_Baringo, "data/Baringo.csv")
```




```{r load data}
my_data <- data.table(read_csv("data/Kitui_Sites.csv"))

```




```{r Long format data frame}
my_data.long_Kitui <- my_data %>%
  pivot_longer(
    cols = starts_with(c("Land","Population", "Population D", "No.of", "Household", "Targeted")),
    names_to = "Site_Data",
    names_prefix = NULL,
    values_to = "amount",
    values_drop_na = TRUE
  )
View(my_data.long_Kitui)

```


```{r Write csv}
fwrite(my_data.long_Kitui, "data/Kitui_long.csv")
```









                                        